const PRODUCT_SERVICE_BASE = 'https://fakestoreapi.com/products';

export const PRODUCT_SERVICE_URL = {
  GET_PRODUCTS: PRODUCT_SERVICE_BASE,
  GET_BY_ID: PRODUCT_SERVICE_BASE,
  CREATE: PRODUCT_SERVICE_BASE,
  UPDATE: PRODUCT_SERVICE_BASE,
  DELETE: PRODUCT_SERVICE_BASE,
};
